name = "adjacent-book-bot"
main = "packages/worker/dist/worker/src/worker.mjs"

workers_dev = true
compatibility_date = "2023-10-24"

build.command = "npm install && npm run build:worker"

#[ai]
#binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "llama2"
database_id = "d3905de9-554a-4861-89c1-eee6317eab67"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"